@startuml
node addml

node dataset
addml -> dataset

node reference {
    node content
    node context
    content -[hidden] context
}

dataset -> reference

package structure {
    package container
    package file
    package folder
    package group
    package field
    package attribute
    package code
}

dataset --> structure
container --> folder
container --> file
file --> group
group -> field
field --> attribute
field --> code

package definitions{
    node catalog
    node definition
    node key
    node "view"
}

catalog -[hidden]- definition
key-[hidden]- view

dataset --> definitions

package types {
    package fileType
    package groupType
    package fieldType
    package attributeType

    fileType -[hidden]- groupType
    fileType -[hidden]- attributeType
    
}

dataset --> types

package processes {
node process
node parameter
}

process --> parameter

dataset --> processes
@enduml
