@startuml
node addml

node dataset{
    node reference {
        node context
        node content

        node additionalElements [
            {{
            node additionalElement
            node property as pp
            node processes
            additionalElement -> additionalElement
        additionalElement --> pp
        pp -> pp
            }}
        ]

        content --> additionalElements
        context --> additionalElements
    }
    node flatFiles{
        node property as pp2
        node flatFile
        node flatFileDefinition
        node recordDefinition
        node keys
        node fieldDefinition
        node code
        node structureTypes {
            node flatFileType
            node recordType
            node fieldType
        }
        node queries
        
        node processes {
            node "Dataset tests"
            node "File tests"
            node "Record tests"
            node "Field tests"
        }

        flatFile -> pp2
        pp2 -u-> pp2
        flatFile -d-> flatFileDefinition
        flatFileDefinition -> recordDefinition
        flatFileDefinition -u-> pp2
        recordDefinition -> fieldDefinition
        recordDefinition -u-> pp2
        recordDefinition --> keys
        fieldDefinition --> code
        fieldDefinition -u-> pp2
    }
    node dataObjects{
        node dataObject
        node property as pp
        node processes as p2
        dataObject -> dataObject
        dataObject  -[hidden]> p2
        dataObject --> pp
        pp -> pp
    }
    reference -[hidden]--> flatFiles
    reference -[hidden] dataObjects
}

addml --> dataset

@enduml
