@startuml
skinparam linetype polyline
skinparam linetype ortho

package "Types" <<Frame>> {
interface structureType

container *-- types

types *-- structureType
structureType <-- fileType
structureType <-- recordType
structureType <-- fieldType

fileType <-- flatFileType
fileType <-- structuredFileType
}

@enduml