@startuml
skinparam linetype polyline
skinparam linetype ortho

class dataset
interface container
dataset *-- container

package "Database" <<Database>> {
container <.. system
system *-- table
system *-- views
system *-- user
}

@enduml