@startuml "database"

package "Database" <<Database>> {
    container <-- system

    package "Tables" <<Rectangle>> {
        system *-- database

        database *-- table

        table *-- column


    }

    package "Views" <<Frame>> {
        system *-- views
    }

    package "Users" <<Frame>> {
        system *-- user
    }
}

@enduml