@startuml

package "Location" <<Rectangle>> {
interface dataFile [[https://github.com/joergen-vs/73027c42-c2cd-4c62-b1f4-2532c0eb8dab/blob/master/usage/aspirations/addml-classes.md#dataFile]]
interface record
interface field

archive *-- folder
archive *-- file

folder <.. dataFolder

file <.. dataFile
dataFile <.. jsonFile
dataFile <.. xmlFile
dataFile <.. delimitedFile
dataFile <.. fixedLengthFile
jsonFile *-- record
record <.. jsonRecord
xmlFile *-- record
record <.. xmlRecord
delimitedFile *-- record
record <.. delimitedRecord
fixedLengthFile *-- record
record <.. fixedLengthRecord

jsonRecord *-- jsonField
jsonField ..> field 
xmlRecord *-- xmlField
xmlField ..> field 
delimitedRecord *-- delimitedField
delimitedField ..> field 
fixedLengthRecord *-- fixedLengthField
fixedLengthField ..> field 
}
@enduml