@startuml
skinparam linetype polyline
skinparam linetype ortho

package "Type" <<Rectangle>> {
interface structureType

archive *-- structureType
structureType <-- fileType
structureType <-- recordType
structureType <-- fieldType

fileType --> flatFileType
}

@enduml