@startuml
skinparam linetype polyline
skinparam linetype ortho

package "Type" <<Frame>> {
interface types

archive *-- types
types <-- fileType
types <-- recordType
types <-- fieldType

fileType <-- flatFileType
fileType <-- structuredFileType
}

@enduml