@startuml
skinparam linetype polyline
skinparam linetype ortho

package "Definition" <<Rectangle>> {
archive *-- definition

interface definition
interface key

definition <-- fileDefinition
definition <-- recordDefinition
definition <-- fieldDefinition

recordDefinition *-- primaryKey
recordDefinition *-- foreignKey
recordDefinition *-- candidateKey
primaryKey --> key
foreignKey --> key
candidateKey --> key

fieldDefinition *-- code
}

@enduml