@startuml
skinparam linetype polyline
skinparam linetype ortho

package "Location" <<Rectangle>> {
interface dataFile
interface record
interface field

archive -- folder
archive -- file

file .. dataFile
dataFile .. xmlFile
dataFile .. delimitedFile
dataFile .. fixedLengthFile
xmlFile -- record
record .. xmlRecord
delimitedFile -- record
record .. delimitedRecord
fixedLengthFile -- record
record .. fixedLengthRecord

xmlRecord -- xmlField
xmlField .. field 
delimitedRecord -- delimitedField
delimitedField .. field 
fixedLengthRecord -- fixedLengthField
fixedLengthField .. field 
}
@enduml