@startuml "database"

package "Database" <<Database>> {
    container <-- system

    package "Tables" <<Rectangle>> {
        system *-- database

        database *-- table
        interface db::key
        
        table *-- db::key
        db::key <-- db::primaryKey
        db::key <-- db::foreignKey
        db::key <-- db::candidateKey

        table *-- column


    }

    package "Views" <<Frame>> {
        system *-- views
    }

    package "Users" <<Frame>> {
        system *-- user
    }
}

@enduml