@startuml "SUF"
skinparam linetype polyline
skinparam linetype ortho

Fagsystem -- Saksbehandling

Saksbehandling -- Foark
Saksbehandling -- Joark
Saksbehandling -- Noark

Noark -- "Noark v3"

Noark -- "Noark v4"
"Noark v4" -- [Noark v4.4.0]
"Noark v4" -- "Noark v4.4.1"

Noark -- "Noark v5"
"Noark v5" -- 'Noark v5.3.1'
"Noark v5" -- 'Noark v5.4.0'
"Noark v5" -- 'Noark v5.5.0'

@enduml